package com.bunkware.bc.boardCafe.Implementation.Query;

public class BoardGameQuery

{
    public static String CREATE_BOARD_GAME = "INSERT INTO boardgame(BOARD_GAME_NAME, BOARD_GAME_DESC, MIN_SUGGESTED_PLAYERS, MAX_SUGGESTED_PLAYERS, PRICE, SUGGESTED_AGE, RENTAL_IMAGE_PATH) " +
            " value(?, ?, ?, ?, ?, ?, ?)";
    public static String GET_BOARD_GAMES_BY_ID = "SELECT BOARD_GAME_ID, BOARD_GAME_NAME, BOARD_GAME_DESC, MIN_SUGGESTED_PLAYERS, MAX_SUGGESTED_PLAYERS, PRICE, SUGGESTED_AGE, RENTAL_IMAGE_PATH FROM boardgame WHERE BOARD_GAME_ID = ? ";
    public static String GET_BOARD_GAMES_BY_NAME = "SELECT BOARD_GAME_ID, BOARD_GAME_NAME, BOARD_GAME_DESC, MIN_SUGGESTED_PLAYERS, MAX_SUGGESTED_PLAYERS, PRICE, SUGGESTED_AGE, RENTAL_IMAGE_PATH FROM boardgame WHERE BOARD_GAME_NAME = ?  ";
    public static String GET_ALL_BOARD_GAMES = "SELECT BOARD_GAME_ID, BOARD_GAME_NAME, BOARD_GAME_DESC, MIN_SUGGESTED_PLAYERS, MAX_SUGGESTED_PLAYERS, PRICE, SUGGESTED_AGE, RENTAL_IMAGE_PATH FROM boardgame ";
    public static String UPDATE_BOARD_GAME = "UPDATE boardgame set BOARD_GAME_NAME = ?, BOARD_GAME_DESC = ?, MIN_SUGGESTED_PLAYERS = ?, MAX_SUGGESTED_PLAYERS = ?, PRICE = ?, SUGGESTED_AGE = ?, RENTAL_IMAGE_PATH = ? WHERE BOARD_GAME_ID = ?\n ";


}
